language: python
python:
  - "2.7"

virtualenv:
  - system_site_packages: true

before_install:
  - sudo apt-get install python-qt4

install:
  - pip install -r requirements.txt

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"


script:
  - py.test
