# vim: sw=2
# Mostly-pristine env
language: c

os: "linux"
dist: "trusty"
sudo: required

# sudo apt-get install python3.4-dev python3.4-venv python3-pyqt4 liblua5.1-0-dev libjpeg8-dev zlib1g-dev git xvfb jq
addons:
  apt:
    packages:
    - libqt4-dev
    - liblua5.1
    - libjpeg8-dev
    - zlib1g-dev
    - jq

install:
  - wget https://github.com/duk3luk3/faf-pyclient-builddeps/releases/download/0.0/pyqt4-faf_4.11.4_travis.deb
  - dpkg -c pyqt4-faf_4.11.4_travis.deb
  - sudo dpkg -i pyqt4-faf_4.11.4_travis.deb
  - python3 -c 'import sys; print(sys.version); print(sys.path)'
  - python3 -c 'import sip; print(sip.__file__)'
  - which virtualenv
  - python3 -c 'import virtualenv; print(virtualenv.__file__)'
  - virtualenv /tmp/venv --system-site-packages
  - . /tmp/venv/bin/activate
  - python3 -c 'import sip; print(sip.__file__)'
  - pip install cx_Freeze python-coveralls
  - pip install -r requirements.txt
  - curl -s https://api.github.com/repos/FAForever/uid/releases/latest | jq -r '.assets[] | select(.name == "faf-uid") | .browser_download_url' | wget -i - -O ./lib/faf-uid


before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - python3 -c 'import sys; print(sys.version); print(sys.path)'
  - export PYTEST_QT_API=pyqt4v2
  - python3 runtests.py -xs --cov src --cov-report term-missing

after_success:
  - coveralls
